/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Auth200Response
 */
export interface Auth200Response {
    /**
     * Whether the token is valid
     * @type {boolean}
     * @memberof Auth200Response
     */
    ok: boolean;
    /**
     * Whether the user is new
     * @type {boolean}
     * @memberof Auth200Response
     */
    _new: boolean;
}

/**
 * Check if a given object implements the Auth200Response interface.
 */
export function instanceOfAuth200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ok" in value;
    isInstance = isInstance && "_new" in value;

    return isInstance;
}

export function Auth200ResponseFromJSON(json: any): Auth200Response {
    return Auth200ResponseFromJSONTyped(json, false);
}

export function Auth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auth200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        '_new': json['new'],
    };
}

export function Auth200ResponseToJSON(value?: Auth200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'new': value._new,
    };
}

