/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetProblem200ResponseProblem } from './GetProblem200ResponseProblem';
import {
    GetProblem200ResponseProblemFromJSON,
    GetProblem200ResponseProblemFromJSONTyped,
    GetProblem200ResponseProblemToJSON,
} from './GetProblem200ResponseProblem';

/**
 * 
 * @export
 * @interface GetProblem200Response
 */
export interface GetProblem200Response {
    /**
     * 
     * @type {GetProblem200ResponseProblem}
     * @memberof GetProblem200Response
     */
    problem: GetProblem200ResponseProblem;
}

/**
 * Check if a given object implements the GetProblem200Response interface.
 */
export function instanceOfGetProblem200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "problem" in value;

    return isInstance;
}

export function GetProblem200ResponseFromJSON(json: any): GetProblem200Response {
    return GetProblem200ResponseFromJSONTyped(json, false);
}

export function GetProblem200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProblem200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'problem': GetProblem200ResponseProblemFromJSON(json['problem']),
    };
}

export function GetProblem200ResponseToJSON(value?: GetProblem200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'problem': GetProblem200ResponseProblemToJSON(value.problem),
    };
}

