/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProblem200ResponseProblemTestcaseInner
 */
export interface GetProblem200ResponseProblemTestcaseInner {
    /**
     * 
     * @type {number}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    sample?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    stdin?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    stdout?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    stdinFile?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProblem200ResponseProblemTestcaseInner
     */
    stdoutFile?: string;
}

/**
 * Check if a given object implements the GetProblem200ResponseProblemTestcaseInner interface.
 */
export function instanceOfGetProblem200ResponseProblemTestcaseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function GetProblem200ResponseProblemTestcaseInnerFromJSON(json: any): GetProblem200ResponseProblemTestcaseInner {
    return GetProblem200ResponseProblemTestcaseInnerFromJSONTyped(json, false);
}

export function GetProblem200ResponseProblemTestcaseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProblem200ResponseProblemTestcaseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'score': json['score'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'sample': !exists(json, 'sample') ? undefined : json['sample'],
        'stdin': !exists(json, 'stdin') ? undefined : json['stdin'],
        'stdout': !exists(json, 'stdout') ? undefined : json['stdout'],
        'stdinFile': !exists(json, 'stdin_file') ? undefined : json['stdin_file'],
        'stdoutFile': !exists(json, 'stdout_file') ? undefined : json['stdout_file'],
    };
}

export function GetProblem200ResponseProblemTestcaseInnerToJSON(value?: GetProblem200ResponseProblemTestcaseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'score': value.score,
        'description': value.description,
        'sample': value.sample,
        'stdin': value.stdin,
        'stdout': value.stdout,
        'stdin_file': value.stdinFile,
        'stdout_file': value.stdoutFile,
    };
}

