/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Problem
 * @export
 * @interface ListProblems200ResponseProblemsInner
 */
export interface ListProblems200ResponseProblemsInner {
    /**
     * Submission count of each status
     * @type {{ [key: string]: number; }}
     * @memberof ListProblems200ResponseProblemsInner
     */
    sub: { [key: string]: number; };
    /**
     * Problem ID
     * @type {string}
     * @memberof ListProblems200ResponseProblemsInner
     */
    id: string;
    /**
     * Problem name
     * @type {string}
     * @memberof ListProblems200ResponseProblemsInner
     */
    name: string;
    /**
     * Problem tags
     * @type {Array<string>}
     * @memberof ListProblems200ResponseProblemsInner
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the ListProblems200ResponseProblemsInner interface.
 */
export function instanceOfListProblems200ResponseProblemsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sub" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "tags" in value;

    return isInstance;
}

export function ListProblems200ResponseProblemsInnerFromJSON(json: any): ListProblems200ResponseProblemsInner {
    return ListProblems200ResponseProblemsInnerFromJSONTyped(json, false);
}

export function ListProblems200ResponseProblemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProblems200ResponseProblemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sub': json['sub'],
        'id': json['id'],
        'name': json['name'],
        'tags': json['tags'],
    };
}

export function ListProblems200ResponseProblemsInnerToJSON(value?: ListProblems200ResponseProblemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub': value.sub,
        'id': value.id,
        'name': value.name,
        'tags': value.tags,
    };
}

