/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Login400Response
 */
export interface Login400Response {
    /**
     * 
     * @type {string}
     * @memberof Login400Response
     */
    message: string;
}

/**
 * Check if a given object implements the Login400Response interface.
 */
export function instanceOfLogin400Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function Login400ResponseFromJSON(json: any): Login400Response {
    return Login400ResponseFromJSONTyped(json, false);
}

export function Login400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Login400ResponseToJSON(value?: Login400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

