/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Me200Response
 */
export interface Me200Response {
    /**
     * User ID
     * @type {string}
     * @memberof Me200Response
     */
    id?: string;
    /**
     * User's email
     * @type {string}
     * @memberof Me200Response
     */
    email?: string;
    /**
     * Token expiration time, in seconds since epoch
     * @type {number}
     * @memberof Me200Response
     */
    exp?: number;
    /**
     * The PEA login URL that this app uses
     * @type {string}
     * @memberof Me200Response
     */
    pea: string;
}

/**
 * Check if a given object implements the Me200Response interface.
 */
export function instanceOfMe200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pea" in value;

    return isInstance;
}

export function Me200ResponseFromJSON(json: any): Me200Response {
    return Me200ResponseFromJSONTyped(json, false);
}

export function Me200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'exp': !exists(json, 'exp') ? undefined : json['exp'],
        'pea': json['pea'],
    };
}

export function Me200ResponseToJSON(value?: Me200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'exp': value.exp,
        'pea': value.pea,
    };
}

