/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface System200ResponseStat
 */
export interface System200ResponseStat {
    /**
     * Number of users
     * @type {number}
     * @memberof System200ResponseStat
     */
    user: number;
    /**
     * Number of submissions
     * @type {number}
     * @memberof System200ResponseStat
     */
    submission: number;
    /**
     * Number of problems
     * @type {number}
     * @memberof System200ResponseStat
     */
    problem: number;
}

/**
 * Check if a given object implements the System200ResponseStat interface.
 */
export function instanceOfSystem200ResponseStat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "submission" in value;
    isInstance = isInstance && "problem" in value;

    return isInstance;
}

export function System200ResponseStatFromJSON(json: any): System200ResponseStat {
    return System200ResponseStatFromJSONTyped(json, false);
}

export function System200ResponseStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): System200ResponseStat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': json['user'],
        'submission': json['submission'],
        'problem': json['problem'],
    };
}

export function System200ResponseStatToJSON(value?: System200ResponseStat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'submission': value.submission,
        'problem': value.problem,
    };
}

