/* tslint:disable */
/* eslint-disable */
/**
 * WASM OJ Wonderland API
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface System200ResponseCfg
 */
export interface System200ResponseCfg {
    /**
     * Number of compilers configured
     * @type {number}
     * @memberof System200ResponseCfg
     */
    compilers: number;
    /**
     * Number of runners configured
     * @type {number}
     * @memberof System200ResponseCfg
     */
    runners: number;
}

/**
 * Check if a given object implements the System200ResponseCfg interface.
 */
export function instanceOfSystem200ResponseCfg(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "compilers" in value;
    isInstance = isInstance && "runners" in value;

    return isInstance;
}

export function System200ResponseCfgFromJSON(json: any): System200ResponseCfg {
    return System200ResponseCfgFromJSONTyped(json, false);
}

export function System200ResponseCfgFromJSONTyped(json: any, ignoreDiscriminator: boolean): System200ResponseCfg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'compilers': json['compilers'],
        'runners': json['runners'],
    };
}

export function System200ResponseCfgToJSON(value?: System200ResponseCfg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'compilers': value.compilers,
        'runners': value.runners,
    };
}

